wandb_version: 1

epochs:
  desc: null
  value: 2000
batch_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0001
dataset:
  desc: null
  value: ../data/astar_2d.npy
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740457472.58087
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.2
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
